HydrogenHourlyMatching: 0
NetworkExpansion: 0
TimeDomainReductionFolder: "TDR_DBSCAN\\_qt_rep_period=1_length_rep_period=8736_eps\\system_epsilon_1.0"
WriteOutputs: "full"
HeterogenousTimesteps: 1
SystemFolder: "system"
EnableJuMPStringNames: false
CO2CapWiggle: 0.0
Trans_Loss_Segments: 1
ModelingtoGenerateAlternativeSlack: 0.1
Solver: "Gurobi"
PoliciesFolder: "policies"
MultiStage: 0
OperationWrapping: 0
CO2CapPeriods: 23
ComputeConflicts: 0
OverwriteResults: 0
ObjScale: 1
ModelingToGenerateAlternatives: 0
OutputFullTimeSeries: 0
MaxCapReq: 0
MinCapReq: 0
CO2Cap: 2
WriteShadowPrices: 1
ModelingToGenerateAlternativeIterations: 3
OutputFullTimeSeriesFolder: "Full_TimeSeries"
HydrogenMinimumProduction: 0
OperationalReserves: 0
ParameterScale: 0
EnergyShareRequirement: 0
PrintModel: 0
TimeDomainReduction: 1
DC_OPF: 0
CapacityReserveMargin: 0
MethodofMorris: 0
StorageVirtualDischarge: 1
MGAAnnualGeneration: 0
StorageLosses: 0
IncludeLossesInESR: 0
ResourcePoliciesFolder: "policy_assignments"
WriteOutputsSettingsDict:
  WriteReserveMarginWithWeights: true
  WriteStorage: true
  WriteStatus: true
  WriteRsv: true
  WriteNetRevenue: true
  WriteNWExpansion: true
  WriteSubsidyRevenue: true
  WriteTimeWeights: true
  WriteVREStor: true
  WriteCO2: true
  WriteESRPrices: true
  WriteReg: true
  WriteCurtailment: true
  WriteCapacityFactor: true
  WriteCommit: true
  WriteStart: true
  WriteReserveMargin: true
  WriteChargingCost: true
  WriteCapacityValue: true
  WriteEnergyRevenue: true
  WriteAngles: true
  WriteFuelConsumption: true
  WriteStorageDual: true
  WriteTransmissionLosses: true
  WriteTransmissionFlows: true
  WriteNSE: true
  WriteCO2Cap: true
  WriteOpWrapLDSStorInit: true
  WriteEmissions: true
  WriteESRRevenue: true
  WriteCapacity: true
  WriteVirtualDischarge: true
  WriteReserveMarginRevenue: true
  WriteOpWrapLDSdStor: true
  WriteMaintenance: true
  WritePower: true
  WriteReliability: true
  WriteCharge: true
  WriteShutdown: true
  WriteHydrogenPrices: true
  WriteReserveMarginSlack: true
  WriteCosts: true
  WriteMaxCapReq: true
  WriteHourlyMatchingPrices: true
  WritePowerBalance: true
  WriteMinCapReq: true
  WritePrice: true
VirtualChargeDischargeCost: 1
UCommit: 0
HourlyMatching: 0
TimestepsPerRepPeriod: 8736
ResourcesFolder: "resources"
