# Gurobi Solver Parameters
# Common solver settings
Feasib_Tol: 1.0e-9           # Constraint (primal) feasibility tolerances.
Optimal_Tol: 1e-9           # Dual feasibility tolerances.
TimeLimit: 11000000             # Limits total time solver.
Pre_Solve: 1                  # Controls presolve level.
Method: 4                     # Algorithm used to solve continuous models (including MIP root relaxation).

#Gurobi-specific solver settings
MIPGap: 1e-9               # Relative (p.u. of optimal) mixed integer optimality tolerance for MIP problems (ignored otherwise).
BarConvTol: 1.0e-10           # Barrier convergence tolerance (determines when barrier terminates).
NumericFocus: 3               # Numerical precision emphasis.
Crossover: -1                 # Barrier crossver strategy.
PreDual: 0                    # Decides whether presolve should pass the primal or dual linear programming problem to the LP optimization algorithm.
AggFill: 10                   # Allowed fill during presolve aggregation.
